server:
  #端口号
  port: 8081
  servlet:
    #应用的访问路径
    context-path: /finance

spring:
  application:
    #应用名称
    name: grape-order

  #数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/grape?useSSL=false&serverTimezone=UTC
    username: root
    password: rain123456

#mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.example.entity